### ISSUE TITLE
KeyError: 'token'

### ISSUE THREAD

**Issue by u1i** [razzo04/samsungtv-api#1]
nice to see a recent project - maybe we can collaborate!

No luck trying to get this to work on a fairly recent U series Samsung TV. I confirmed that http://192.168.1.XXX:8001/api/v2/ gives me decent output.

Running your example (assuming it's Python3?) I am getting:

python example.py 
Traceback (most recent call last):
  File "example.py", line 4, in <module>
    with SamsungTV("192.168.1.210") as tv:
  File "[xxx]/samsungtv-api/samsungtvremote/samsungtvr.py", line 46, in __init__
    if response["data"]["token"] != None:
KeyError: 'token'

**Comment by u1i** [comment]
nevermind. Works with https://github.com/razzo04/samsung-tv-api
